[package]
name = "ckb-benches"
version = "0.2.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"

[dependencies]


[dev-dependencies]
criterion = "0.2"
ckb-pow = { path = "../pow" }

[[bench]]
name = "cuckoo"
harness = false
